### ISSUE TITLE
php tags in site.html

### ISSUE THREAD

**Issue by dulabs** [evolutionscript/HelpDeskZ-1.0#2]
found some issue with template in views/client/site.html
in line 28
`<li><a href="{{ getUrl('news') }}" <?php echo {% if controller == 'news' %}class="current"{% endif %}>{{ LANG.NEWS }}</a></li>`

become

`  <li><a href="{{ getUrl('news') }}"  {% if controller == 'news' %}class="current"{% endif %}>{{ LANG.NEWS }}</a></li>`
           
and also in line 47, remove this
`<?php if($client_status != 1){ ?>`           

https://github.com/evolutionscript/HelpDeskZ-1.0/blob/master/views/client/site.html

**Comment by evolutionscript** [comment]
Thanks, file has been updated.
