### ISSUE TITLE
Missing config.php.new ?

### ISSUE THREAD

**Issue by g03l** [evolutionscript/HelpDeskZ-1.0#25]
Hi,
I'm trying to install the package, but the downloaded package is missing config.php.new so I'm not sure what should be inside config.php.

Can you help please?
Regards,
goel

**Comment by tschiemer** [comment]
`config.php` is created and populated directly by the installer script.

thus to create just visit the folder `/install` of your helpdeskz installation in your browser

**Comment by g03l** [comment]
Argh... how silly of me :-/ Thanks!

**Comment by issnteacher** [comment]
The install process doesnt create the file for me ... Simply won't install on Ubuntu 16 with Apache 2 and php7 and mysql 5

**Comment by tschiemer** [comment]
Are the necessary filesystem permission set for the webserver user?

The following is the code which writes the config file, you can try using a small test-php file using the same functions (`file_put_contents(..)`) - if that doesn't work it's not a problem of the installer.

```
function helpdeskz_saveConfigFile($db_host, $db_name, $db_user, $db_password, $db_prefix, $db_type){
	$content = '<?php
	$config[\'Database\'][\'dbname\'] = \''.$db_name.'\';
	$config[\'Database\'][\'tableprefix\'] = \''.$db_prefix.'\';
	$config[\'Database\'][\'servername\'] = \''.$db_host.'\';
	$config[\'Database\'][\'username\'] = \''.$db_user.'\';
	$config[\'Database\'][\'password\'] = \''.str_replace("'","\'", $db_password).'\';
	$config[\'Database\'][\'type\'] = \''.$db_type.'\';
	?>';
	if ( ! file_put_contents(HELPDESKZ_PATH . 'includes/config.php', $content) )
	{
		return false;
	}else{
		return true;	
	}
}
```
