### ISSUE TITLE
Characters with accents/symbols/Ñ... not showing correctly in search results

### ISSUE THREAD

**Issue by mrluisiko99** [evolutionscript/HelpDeskZ-1.0#5]
![captura](https://cloud.githubusercontent.com/assets/9170655/7789238/086e9132-025a-11e5-9436-ea4679fa90c6.PNG)

**Comment by evolutionscript** [comment]
Hi, thanks for your report, we're going to fix this asap.

**Comment by evolutionscript** [comment]
Fixed in v1.0.2
